# Phase1/Phase2 Weekly Report Schedule Setup
# phase1_weekly_report.py --phase2 を週次で実行するタスクを登録

param(
    [string]$ScriptDir = "C:\Users\mana4\Desktop\manaos_integrations",
    [string]$PythonPath = "python",
    [string]$TaskName = "Phase1_Weekly_Report",
    [string]$ScheduleTime = "09:00",
    [string]$ScheduleDay = "Sunday",
    [switch]$WithSave,
    [switch]$Unregister
)

$ErrorActionPreference = "Stop"

try {
    chcp 65001 | Out-Null
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
    $OutputEncoding = [System.Text.UTF8Encoding]::new()
} catch {}

Write-Host "Phase1 Weekly Report Schedule Setup" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

if ($Unregister) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Task '$TaskName' unregistered." -ForegroundColor Green
    } else {
        Write-Host "Task '$TaskName' not found." -ForegroundColor Yellow
    }
    exit 0
}

$reportScript = Join-Path $ScriptDir "phase1_weekly_report.py"
if (-not (Test-Path $reportScript)) {
    Write-Host "ERROR: Script not found: $reportScript" -ForegroundColor Red
    exit 1
}

Write-Host "Script Directory: $ScriptDir" -ForegroundColor Green
Write-Host "Python: $PythonPath" -ForegroundColor Green
Write-Host "Task Name: $TaskName" -ForegroundColor Green
Write-Host "Schedule: Every $ScheduleDay at $ScheduleTime" -ForegroundColor Green
Write-Host ""

$runnerScript = Join-Path $ScriptDir "run_phase1_weekly_report.ps1"
$archiveScript = Join-Path $ScriptDir "phase1_low_sat_archive.py"
$reportArgs = "--phase2"
if ($WithSave) { $reportArgs = "--save --condition on --tag weekly " + $reportArgs }

$runnerContent = @"
# Phase1 Weekly Report Runner (generated by schedule_phase1_weekly_report.ps1)
try {
    chcp 65001 | Out-Null
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
    `$OutputEncoding = [System.Text.UTF8Encoding]::new()
} catch {}
Set-Location -LiteralPath '$ScriptDir'
& $PythonPath '$reportScript' $reportArgs
& $PythonPath '$archiveScript'
"@
$runnerContent | Out-File -FilePath $runnerScript -Encoding UTF8

$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File `"$runnerScript`"" -WorkingDirectory $ScriptDir
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $ScheduleDay -At $ScheduleTime
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

$existingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existingTask) {
    Write-Host "Removing existing task..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

try {
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Description "Phase1/Phase2 weekly report (aggregate + low_satisfaction + memo summary)" -Force | Out-Null
    Write-Host "Scheduled task registered successfully!" -ForegroundColor Green
    $nextRun = (Get-ScheduledTask -TaskName $TaskName).NextRunTime
    Write-Host "Next Run: $nextRun" -ForegroundColor Yellow
    Write-Host "Unregister: Unregister-ScheduledTask -TaskName $TaskName" -ForegroundColor Gray
} catch {
    Write-Host "ERROR: Task registration failed" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    exit 1
}
