#!/usr/bin/env python3
"""
Trinity System専用 Notion連携ヘルパー
各エージェントが簡単にNotionに記録できる

使い方:
  # Remiが設計書を記録
  trinity_notion.py remi-log "プロジェクト名" "設計内容"
  
  # Lunaが実装完了を記録
  trinity_notion.py luna-log "タスク名" "実装内容"
  
  # Minaがレビュー結果を記録
  trinity_notion.py mina-log "タスク名" "レビュー結果"
  
  # Ariaがナレッジを記録
  trinity_notion.py aria-log "質問タイトル" "回答内容"
  
  # 検索
  trinity_notion.py search "キーワード"
"""

import os
import sys
import json
from datetime import datetime
from notion_client import NotionClient

# Trinity専用のNotion設定
TRINITY_CONFIG = {
    # 各エージェント用のページID（要設定）
    "remi_parent_id": None,  # Remi用親ページID
    "luna_parent_id": None,  # Luna用親ページID
    "mina_parent_id": None,  # Mina用親ページID
    "aria_parent_id": None,  # Aria用親ページID
    
    # デフォルト設定
    "auto_create": True,  # 親ページがない場合は自動作成
    "backup_to_local": True,  # ローカルにもバックアップ
}

class TrinityNotion:
    def __init__(self):
        self.client = NotionClient()
        self.config = TRINITY_CONFIG
        self.backup_dir = "/root/trinity_workspace/logs/notion_backup"
        os.makedirs(self.backup_dir, exist_ok=True)
    
    def backup_to_local(self, agent: str, title: str, content: str):
        """ローカルにもバックアップ"""
        if not self.config["backup_to_local"]:
            return
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{agent}_{timestamp}.md"
        filepath = os.path.join(self.backup_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"# {title}\n\n")
            f.write(f"**Agent**: {agent}\n")
            f.write(f"**Timestamp**: {datetime.now().isoformat()}\n\n")
            f.write("---\n\n")
            f.write(content)
        
        return filepath
    
    def log_to_notion(self, agent: str, title: str, content: str) -> dict:
        """Notionにログを記録"""
        # ローカルバックアップ
        backup_path = self.backup_to_local(agent, title, content)
        
        # タイトルにタイムスタンプとエージェント名を追加
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        full_title = f"[{agent.upper()}] {title} - {timestamp}"
        
        try:
            # 検索して既存のTrinityワークスペースを探す
            search_results = self.client.search("Trinity Workspace")
            
            parent_id = None
            if search_results.get('results'):
                # 最初に見つかったページを親として使用
                parent_id = search_results['results'][0]['id']
            else:
                # なければ検索結果の最初のページを使う
                all_pages = self.client.search()
                if all_pages.get('results'):
                    parent_id = all_pages['results'][0]['id']
            
            if parent_id:
                result = self.client.create_page(parent_id, full_title, content)
                return {
                    "success": True,
                    "page_id": result['id'],
                    "url": result['url'],
                    "backup": backup_path
                }
            else:
                return {
                    "success": False,
                    "error": "親ページが見つかりません",
                    "backup": backup_path
                }
                
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "backup": backup_path
            }
    
    def remi_log(self, project_name: str, strategy_content: str):
        """Remi用：設計書をログ"""
        content = f"""## プロジェクト: {project_name}

### 設計内容
{strategy_content}

### 関連ファイル
- strategy.md
- tasks.json

---
Generated by Remi (Trinity System)
"""
        return self.log_to_notion("Remi", f"設計: {project_name}", content)
    
    def luna_log(self, task_name: str, implementation: str):
        """Luna用：実装完了をログ"""
        content = f"""## タスク: {task_name}

### 実装内容
{implementation}

### ステータス
✅ 実装完了 → レビュー待ち

---
Generated by Luna (Trinity System)
"""
        return self.log_to_notion("Luna", f"実装: {task_name}", content)
    
    def mina_log(self, task_name: str, review_result: str):
        """Mina用：レビュー結果をログ"""
        content = f"""## タスク: {task_name}

### レビュー結果
{review_result}

---
Generated by Mina (Trinity System)
"""
        return self.log_to_notion("Mina", f"レビュー: {task_name}", content)
    
    def aria_log(self, question: str, answer: str, tags: str = ""):
        """Aria用：Q&Aをログ"""
        content = f"""## 質問
{question}

## 回答
{answer}

## タグ
{tags}

---
Generated by Aria (Trinity System)
"""
        return self.log_to_notion("Aria", f"Q&A: {question[:50]}", content)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    trinity = TrinityNotion()
    command = sys.argv[1]
    
    try:
        if command == "remi-log":
            if len(sys.argv) < 4:
                print("使い方: trinity_notion.py remi-log <project_name> <content>")
                sys.exit(1)
            result = trinity.remi_log(sys.argv[2], sys.argv[3])
            
        elif command == "luna-log":
            if len(sys.argv) < 4:
                print("使い方: trinity_notion.py luna-log <task_name> <content>")
                sys.exit(1)
            result = trinity.luna_log(sys.argv[2], sys.argv[3])
            
        elif command == "mina-log":
            if len(sys.argv) < 4:
                print("使い方: trinity_notion.py mina-log <task_name> <content>")
                sys.exit(1)
            result = trinity.mina_log(sys.argv[2], sys.argv[3])
            
        elif command == "aria-log":
            if len(sys.argv) < 4:
                print("使い方: trinity_notion.py aria-log <question> <answer> [tags]")
                sys.exit(1)
            tags = sys.argv[4] if len(sys.argv) > 4 else ""
            result = trinity.aria_log(sys.argv[2], sys.argv[3], tags)
            
        elif command == "search":
            query = sys.argv[2] if len(sys.argv) > 2 else ""
            results = trinity.client.search(query)
            from notion_client import format_search_results
            print(format_search_results(results))
            sys.exit(0)
            
        else:
            print(f"不明なコマンド: {command}")
            print(__doc__)
            sys.exit(1)
        
        # 結果表示
        if result['success']:
            print(f"✅ Notionに記録成功！")
            print(f"   URL: {result['url']}")
            print(f"   Backup: {result['backup']}")
        else:
            print(f"⚠️  Notion記録失敗（ローカルバックアップは成功）")
            print(f"   Error: {result['error']}")
            print(f"   Backup: {result['backup']}")
            
    except Exception as e:
        print(f"エラー: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()

